# Generated by Django 5.0.2 on 2024-04-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_register',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Doctor_name', models.CharField(max_length=50)),
                ('Doctor_mobile_no', models.CharField(max_length=50)),
                ('Doctor_email_id', models.EmailField(max_length=40)),
                ('Doctor_gender', models.CharField(max_length=50)),
                ('Doctor_blood_group', models.CharField(max_length=50)),
                ('Doctor_Qualification', models.CharField(max_length=50)),
                ('Doctor_specialist', models.CharField(max_length=50)),
                ('Doctor_age', models.CharField(max_length=50)),
                ('Doctor_country', models.CharField(max_length=50)),
                ('Doctor_state', models.CharField(max_length=50)),
                ('Doctor_district', models.CharField(max_length=50)),
                ('Doctor_town', models.CharField(max_length=50)),
                ('Doctor_register_date', models.DateTimeField(auto_now_add=True)),
                ('Doctor_password', models.CharField(max_length=50)),
            ],
        ),
    ]
