# Generated by Django 5.0.2 on 2024-04-18 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_medical_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_records',
            name='patient_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medical_records',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient_register'),
        ),
    ]
