# Generated by Django 5.0.2 on 2024-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_medical_records_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_records',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medical_records',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
