# Generated by Django 5.0.2 on 2024-04-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_medical_records_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_records',
            name='patient_name',
            field=models.CharField(max_length=50),
        ),
    ]
