# Generated by Django 5.0.2 on 2024-04-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_health_isssue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_issue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('health_issue', models.CharField(max_length=20)),
                ('issue_rate', models.CharField(max_length=20)),
                ('Bp', models.CharField(max_length=20)),
                ('sugar', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Health_isssue',
        ),
    ]
