# Generated by Django 5.0.2 on 2024-04-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_health_issue_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chekup_list',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='health_issue',
            name='patient_name',
            field=models.CharField(max_length=30),
        ),
    ]
