# Generated by Django 5.0.2 on 2024-04-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_appointment_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_list',
            name='email_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
